[DEFAULT]
workspace_url = [YOUR_DATABRICKS_WORKSPACE_URL]
dqx_config_catalog = [YOUR_DQX_CATALOG_NAME]
dqx_config_schema = [YOUR_DQX_SCHEMA_NAME]
ignore_schemas = [SCHEMAS_TO_IGNORE_SEPARATED_BY_PIPE]

[AI_ASSISTANT]
llm_model = [YOUR_LLM_MODEL_PATH_OR_NAME]

[SQL]
server_hostname = [YOUR_SQL_SERVER_HOSTNAME]
http_path = [YOUR_SQL_WAREHOUSE_HTTP_PATH]
token = [YOUR_DATABRICKS_PERSONAL_ACCESS_TOKEN]
job_id = [YOUR_DATABRICKS_JOB_ID]

[EMAIL]
address = [SENDER_EMAIL_ADDRESS]
copy_to = [RECIPIENT_EMAIL_1],[RECIPIENT_EMAIL_2]
password = [APP_SPECIFIC_PASSWORD]
smtp_server = [SMTP_SERVER_URL]
smtp_port = [SMTP_PORT_NUMBER]
