[DEFAULT]
dqx_config_catalog = <YOUR_CATALOG_NAME>
dqx_config_schema = <YOUR_SCHEMA_NAME>
ignore_schemas = <SCHEMAS_TO_IGNORE>


[WORKSPACE]
workspace_url = <YOUR_WORKSPACE_URL>
job_id = <YOUR_JOB_ID>
dashboard_id = <YOUR_DASHBOARD_ID>
org_id = <YOUR_ORG_ID>


[AI_ASSISTANT]
llm_model = <YOUR_LLM_MODEL_PATH>


[SQL]
server_hostname = <YOUR_SERVER_HOSTNAME>
http_path = <YOUR_HTTP_PATH>
token = <YOUR_DATABRICKS_TOKEN>


[EMAIL]
address = <YOUR_EMAIL_ADDRESS>
copy_to = <YOUR_CC_EMAIL_ADDRESS>
password = <YOUR_EMAIL_APP_PASSWORD>
smtp_server = <YOUR_SMTP_SERVER>
smtp_port = <YOUR_SMTP_PORT>
